using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Numerics;
//Austin Marino-11507852
namespace NotepadApp
{
    class FibonacciTextReader: System.IO.TextReader
    {
        public int MaxLines { get; private set; }
        public FibonacciTextReader(int maxLines)
        {
            this.MaxLines = maxLines;
        }

        public string ReadLine(BigInteger line, int count)
        {
            //returns the string value of count and line if count is less than or equal to MaxLines
            if (count.Equals(this.MaxLines+1))
            {
                return null;
            }
            return $"{count}: {line}\n";
        }
        public override string ReadToEnd()
        {
            StringBuilder lines = new StringBuilder();
            //Used to hold Large integer values generated by fibonacci sequence
            BigInteger one = new BigInteger(0);
            BigInteger two = new BigInteger(1);
            BigInteger result = new BigInteger(0);
            int count = 0;
            //Fibonacci algorithm
            while(count < this.MaxLines)
            {
                lines.Append(ReadLine(result, ++count));
                one = two;
                two = result;
                result = one + two;
            }
            //Converts stringbuilder containing fibonacci values to a string
            return lines.ToString();
        }

    }
}
